server:
  port: 8081
  tomcat:
    max-swallow-size: 10MB

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.99.138.155:3306/db_myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: db_myblog
    password: YlIm6+QmHefo+TNxSzSylw==
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.gujunbin: debug
  file: log/blog-dev.log



