server:
  port: 8081
  tomcat:
    max-swallow-size: 10MB

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wf1GGDEdzE1eaaMEUev4Cw==
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: info
    com.gujunbin: info
  file: log/blog.log


